// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZxmA0PRinLfq_Z7i4yA_RGl2hB2tMUk',
    appId: '1:580733057416:web:a4d8ae6985c380d082223d',
    messagingSenderId: '580733057416',
    projectId: 'bitkuay-29067',
    authDomain: 'bitkuay-29067.firebaseapp.com',
    storageBucket: 'bitkuay-29067.firebasestorage.app',
    measurementId: 'G-3JCW13DVTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn16nmHslCkcIBLTHeKk5gksHP1OjNVSQ',
    appId: '1:580733057416:android:33e8f8cead648d8682223d',
    messagingSenderId: '580733057416',
    projectId: 'bitkuay-29067',
    storageBucket: 'bitkuay-29067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25xmYNfoI55SHk-8DH57n4Yw_3tL5jhg',
    appId: '1:580733057416:ios:8cf82b55ba20b46d82223d',
    messagingSenderId: '580733057416',
    projectId: 'bitkuay-29067',
    storageBucket: 'bitkuay-29067.firebasestorage.app',
    iosBundleId: 'com.example.nattanon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25xmYNfoI55SHk-8DH57n4Yw_3tL5jhg',
    appId: '1:580733057416:ios:8cf82b55ba20b46d82223d',
    messagingSenderId: '580733057416',
    projectId: 'bitkuay-29067',
    storageBucket: 'bitkuay-29067.firebasestorage.app',
    iosBundleId: 'com.example.nattanon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLZxmA0PRinLfq_Z7i4yA_RGl2hB2tMUk',
    appId: '1:580733057416:web:41cc14290a06b2b282223d',
    messagingSenderId: '580733057416',
    projectId: 'bitkuay-29067',
    authDomain: 'bitkuay-29067.firebaseapp.com',
    storageBucket: 'bitkuay-29067.firebasestorage.app',
    measurementId: 'G-21SRWQPJD7',
  );
}
